### PR TITLE
Add model watch option

### PR DESCRIPTION
**Pull request by drewhayward**
Added the ability to "watch" the allennlp model using the `wand.watch()` interface. It works through the same callback that the basic scenario uses.

### CODE REVIEW

**Comment by dhruvdcoder** [comment]
@drewhayward Thanks for the PR. I am merging it through another branch in the repo so that the tests can run with my wandb api key.

**Comment by drewhayward** [comment]
Just an FYI, it appears the `wandb.watch()` is leaking memory when used in this way... Not sure why. I'll have to look into it eventually

**Comment by dhruvdcoder** [comment]
Thanks for the info @drewhayward. I guess I haven't been using watch() enough to notice the issue. Feel free to create a PR if you are able to find a solution.

**Comment by drewhayward** [comment]
Turned out to be unrelated. The feature should be fine

**Pull request merged**
